# Generated by Django 6.0.3 on 2026-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsession',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
