services:
  db:
    image: postgres:16
    container_name: regform_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: regform_db
      POSTGRES_USER: regform_user
      POSTGRES_PASSWORD: regform_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: